window.games = [
  {
    letter: 'A',
    otherLetters: [
      'D',
      'E',
      'H',
      'I',
      'K',
      'V'
    ],
    bigWord: 'KHEDIVA',
    words: [
      'AAHED',
      'ADDED',
      'AHEAD',
      'AHED',
      'DADA',
      'DADDED',
      'DEAD',
      'DEADED',
      'DEADHEAD',
      'DEADHEADED',
      'HADDIE',
      'HADE',
      'HADED',
      'HADEDAH',
      'HAED',
      'HEAD',
      'HEADED',
      'KHEDIVA'
    ]
  },
  {
    letter: 'A',
    otherLetters: [
      'B',
      'D',
      'E',
      'M',
      'S',
      'T'
    ],
    bigWord: 'BEDMATES',
    words: [
      'ABBA',
      'ABBED',
      'ABED',
      'BAAED',
      'BABA',
      'BADE',
      'BAMMED',
      'BEAD',
      'BEADED',
      'BEAMED',
      'BEDAD',
      'BEDMATES',
      'BEMAD',
      'BEMADAM',
      'BEMADAMED',
      'BEMADAMS',
      'BEMADDED',
      'BEMADS',
      'DABBA',
      'DABBED',
      'EMBASED',
      'EMBASSADE',
      'EMBASSADES',
      'SAMBAED'
    ]
  },
  {
    letter: 'I',
    otherLetters: [
      'C',
      'E',
      'H',
      'R',
      'T',
      'Y'
    ],
    bigWord: 'ERYTHRITIC',
    words: [
      'CHEERIER',
      'CHERRIER',
      'CHERTIER',
      'CHICER',
      'CHICHIER',
      'CHIRRE',
      'CHITTER',
      'CHITTIER',
      'CITHER',
      'ERETHIC',
      'ERETHITIC',
      'ERYTHRITIC',
      'ETHERIC',
      'HERETIC',
      'HITCHER',
      'HITCHIER',
      'ITCHIER',
      'RECHIE',
      'REECHIE',
      'REECHIER',
      'RICHER',
      'RICHTER',
      'TECHIER',
      'TETCHIER',
      'THRICE',
      'TICHIER',
      'TITCHIER',
      'TRICHITE'
    ]
  },
  {
    letter: 'T',
    otherLetters: [
      'C',
      'I',
      'N',
      'O',
      'S',
      'X'
    ],
    bigWord: 'NONTOXICS',
    words: [
      'COCTIONS',
      'COITIONS',
      'CONCOCTIONS',
      'CONSIST',
      'CONSISTS',
      'INTINCTIONS',
      'ISOTONIC',
      'NICOTINS',
      'NONTOXICS',
      'SCONTION',
      'SCONTIONS',
      'STICTION',
      'STICTIONS',
      'TOCSIN',
      'TOCSINS',
      'TONICS'
    ]
  },
  {
    letter: 'L',
    otherLetters: [
      'A',
      'B',
      'D',
      'E',
      'N',
      'Y'
    ],
    bigWord: 'BELLYBAND',
    words: [
      'ABLED',
      'ADDABLE',
      'BABBLED',
      'BALDED',
      'BALED',
      'BALLADE',
      'BALLADED',
      'BALLED',
      'BEADLE',
      'BEDABBLE',
      'BEDABBLED',
      'BEDDABLE',
      'BELLYBAND',
      'BENDABLE',
      'BLABBED',
      'BLADDED',
      'BLADE',
      'BLADED',
      'BLANDED',
      'BLENDABLE',
      'DABBLE',
      'DABBLED',
      'ENABLED',
      'LABELED',
      'LABELLED',
      'LEADABLE',
      'LENDABLE'
    ]
  },
  {
    letter: 'T',
    otherLetters: [
      'A',
      'D',
      'E',
      'I',
      'R',
      'Y'
    ],
    bigWord: 'DIETARY',
    words: [
      'AIRDATE',
      'AIRTED',
      'ATTIRED',
      'ATTRITED',
      'ATTRITTED',
      'DIATRETA',
      'DIETARY',
      'ERADIATE',
      'ERADIATED',
      'IRRADIATE',
      'IRRADIATED',
      'IRRITATED',
      'ITERATED',
      'RADIATE',
      'RADIATED',
      'RAITED',
      'REITERATED',
      'RERADIATE',
      'RERADIATED',
      'TARDIED',
      'TARDIER',
      'TARRIED',
      'TETRADITE',
      'TIARAED',
      'TIRADE',
      'TITRATED',
      'TRADIE',
      'TRIRADIATE',
      'TRITIATED'
    ]
  },
  {
    letter: 'A',
    otherLetters: [
      'B',
      'D',
      'E',
      'S',
      'W',
      'X'
    ],
    bigWord: 'BEESWAXED',
    words: [
      'ABASED',
      'ABBA',
      'ABBED',
      'ABED',
      'BAAED',
      'BABA',
      'BADASSED',
      'BADASSES',
      'BADE',
      'BASED',
      'BASSED',
      'BEAD',
      'BEADED',
      'BEADS',
      'BEDAD',
      'BEESWAXED',
      'DABBA',
      'DABBED',
      'DEBASE',
      'DEBASED',
      'DEBASES',
      'SABBED',
      'SABED',
      'SEABED',
      'SEABEDS',
      'SWABBED'
    ]
  },
  {
    letter: 'B',
    otherLetters: [
      'D',
      'E',
      'O',
      'P',
      'R',
      'T'
    ],
    bigWord: 'BEDROPT',
    words: [
      'BEBOPPED',
      'BEDDED',
      'BEDE',
      'BEDROP',
      'BEDROPPED',
      'BEDROPT',
      'BOBBED',
      'BODE',
      'BODED',
      'BOOBED',
      'BOOED',
      'BOPPED',
      'DEBE',
      'DOBBED',
      'DOBE',
      'EBBED',
      'PROBED',
      'REPROBED'
    ]
  },
  {
    letter: 'A',
    otherLetters: [
      'D',
      'E',
      'M',
      'P',
      'U',
      'Y'
    ],
    bigWord: 'MADEUPPY',
    words: [
      'ADDED',
      'ADDEEM',
      'ADDEEMED',
      'ADEEM',
      'ADEEMED',
      'AMPED',
      'DADA',
      'DADDED',
      'DAME',
      'DAMME',
      'DAMMED',
      'DAMPED',
      'DEAD',
      'DEADED',
      'EDAMAME',
      'EDEMA',
      'MAAED',
      'MADAME',
      'MADAMED',
      'MADDED',
      'MADE',
      'MADEUPPY',
      'MAPPED',
      'MEAD',
      'UPMADE'
    ]
  },
  {
    letter: 'A',
    otherLetters: [
      'L',
      'N',
      'R',
      'S',
      'U',
      'Y'
    ],
    bigWord: 'URANYLS',
    words: [
      'ALAN',
      'ANAL',
      'ANNAL',
      'ANNULARS',
      'LALL',
      'LALLAN',
      'LANA',
      'LARN',
      'LARNS',
      'LUNARS',
      'NALA',
      'NALLA',
      'RANULAS',
      'SNARL',
      'SNARLS',
      'UNSNARL',
      'UNSNARLS',
      'URANYLS'
    ]
  }
];
